title:              Jash Shah Blogs
email:              jash28582@gmail.com
description:        A small place on this vast network for me to write about my experiences with tech, people, place and life!
author:             Jash Shah
<<<<<<< HEAD
baseurl:            "/Blogs"
url:                "jash_shah.github.io"
=======
baseurl:            "/home"
url:                "https://jash_shah.github.io"
>>>>>>> parent of c80acc8... Changed URL

# Social Profiles
twitter_username:   
github_username:    Jash-Shah
facebook_username:  
instagram_username:  s_jash
linkedin_username:  Jash Shah

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

theme: jekyll-theme-clean-blog